#!/usr/bin/env bash
set -eu
IVY_CACHE_ARG=""
SBT_CACHE_ARG=""

IVY_CACHE=${IVY_CACHE-}
SBT_CACHE=${SBT_CACHE-}

if [ -n "$IVY_CACHE" ]; then
	IVY_CACHE_ARG="-Dsbt.ivy.home=$IVY_CACHE"
fi

if [ -n "$SBT_CACHE" ]; then
	SBT_CACHE_ARG="-Dsbt.boot.directory=$SBT_CACHE"
fi

echo "Running sbt -DtestLog.level=INFO $IVY_CACHE_ARG $SBT_CACHE_ARG $@"
sbt -DtestLog.level=INFO "$IVY_CACHE_ARG" "$SBT_CACHE_ARG" $@
